name: Persistent SSH Tunnels
version: 0.0.2
slug: tunnels
init: false
description: Establishes persistent SSH tunnels with automatic reconnection for secure remote access.
url: https://github.com/mamogaaa/hassio-addons
stage: experimental
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: system
boot: auto
map:
  - share:rw
options:
  server: ""
  port: 22
  tunnels:
    - tunnel: home:80:172.30.32.1:8123
  ServerKeepAliveInterval: 3
schema:
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
  server: str
  port: int
  user: str?
  force_new_sshkey: bool?
  tunnels:
    - tunnel: str
  sni_proxy: bool?
  tcp_alias: bool?
  ServerKeepAliveInterval: int
